import Image from "next/image";
import Head from "next/head";


export default function Home() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-1 pb-0 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)] text-center">
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="generated by sagar ghat" />
        <meta name="" content="" key="title" />
      </Head>


      <main className="flex flex-col items-center gap-8">
        <div>
          <h1 className="text-4xl font-bold">Hunter Coding</h1>
          <h4 className="mt-4 text-lg text-gray-600">A blog for hunting coder by hunting coder</h4>
        </div>

        <div>
          <Image
            className="dark:invert"
            src="/coder.jpg"
            alt="coding logo"
            width={400}
            height={400}
            priority
          />
        </div>

        <div className="flex flex-col items-center gap-6 max-w-2xl">
          {[1, 2, 3, 4].map((_, i) => (
            <div key={i} className="bg-gray-100 p-4 rounded-lg shadow w-full">
              <h2 className="text-2xl font-semibold mb-2">How to learn JavaScript in 2022</h2>
              <p className="text-gray-700">JavaScript is one of the most famous languages.</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
